version: 2
jobs:
  build:
    docker:
      - image: circleci/node
    steps:
      - run: 
          name: Show yarn version
          command: yarn --version
      - run:
          name: Show node version
          command: node --version
      - run:
          name: Install rsync
          command: sudo apt-get update && sudo apt-get install rsync
      - add_ssh_keys:
            fingerprints:
                - "52:80:3c:56:56:20:f2:83:a7:02:7e:e6:e7:aa:50:c7"
      - run: 
          name: Add resamvi.de to trusted hosts
          command: ssh-keyscan resamvi.de >> ~/.ssh/known_hosts
      - checkout
      - run: 
          name: Install dependencies
          command: yarn install
      - run: 
          name: Build website
          command: yarn build
      - run: 
          name: Upload website
          command: rsync -va dist/ julien@resamvi.de:/var/www/resamvi.de
      - store_artifacts:
          path: dist/