# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on: [push, workflow_dispatch]

jobs:
  build:  
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - 
        name: Checkout Repo
        uses: actions/checkout@v2
      
      - 
        name: Run a one-line script
        run: ls
      
      - 
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: registry.resamvi.io
          username: ${{ secrets.USER }}
          password: ${{ secrets.PASS }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: registry.resamvi.io/resamvi.io:latest
      -
        name: Pull and update
          uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: docker ps
